### ISSUE TITLE
Get details for a Spot from an id

### ISSUE THREAD

**Issue by heather-yaple** [heather-yaple/auth-me-project#10]
Returns the details of a spot specified by its id.

- [ ]  Successful response includes data only for the specified spot
- [ ]  Spot data returned includes the id, ownerId, address, city, state, country, lat, lng, name, description, price, createdAt, and updatedAt
- [ ]  Spot data returns aggregate data for numReviews and avgStarRating
- [ ]  Spot data returns associated data for SpotImages, an array of image data including the id, url, and preview
- [ ]  Spot data returns associated data for Owner, including the id, firstName, and lastName
- [ ]  Error response with status 404 is given when a spot does not exist with the provided id

**Comment by joe-corcoran** [comment]
Get details of a Spot from an id
Returns the details of a spot specified by its id.

Require Authentication: false

Request

Method: GET
Route path: /api/spots/:spotId
Body: none
Successful Response

Status Code: 200

Headers:

Content-Type: application/json
Body:

{
  "id": 1,
  "ownerId": 1,
  "address": "123 Disney Lane",
  "city": "San Francisco",
  "state": "California",
  "country": "United States of America",
  "lat": 37.7645358,
  "lng": -122.4730327,
  "name": "App Academy",
  "description": "Place where web developers are created",
  "price": 123,
  "createdAt": "2021-11-19 20:39:36",
  "updatedAt": "2021-11-19 20:39:36" ,
  "numReviews": 5,
  "avgStarRating": 4.5,
  "SpotImages": [
    {
      "id": 1,
      "url": "image url",
      "preview": true
    },
    {
      "id": 2,
      "url": "image url",
      "preview": false
    }
  ],
  "Owner": {
    "id": 1,
    "firstName": "John",
    "lastName": "Smith"
  }
}
Error response: Couldn't find a Spot with the specified id

Status Code: 404

Headers:

Content-Type: application/json
Body:

{
  "message": "Spot couldn't be found"
}
