### ISSUE TITLE
Create a Review for a Spot based on the Spot's id

### ISSUE THREAD

**Issue by heather-yaple** [heather-yaple/auth-me-project#13]
Create and return a new review for a spot specified by id.

- [x]  An authenticated user is required for a successful response
- [x]  New review exists in the database after request
- [x]  Review data returned includes the id, userId, spotId, review, stars, createdAt, and updatedAt
- [x]  Error response with status 400 is given when body validations for the review or stars are violated
- [x]  Error response with status 404 is given when a spot does not exist with the provided id
- [x]  Error response with status 403 is given when a review already exists for the spot from the current user

**Comment by joe-corcoran** [comment]
Create a Review for a Spot based on the Spot's id
Create and return a new review for a spot specified by id.

Require Authentication: true

Request

Method: POST

Route path: /api/spots/:spotId/reviews

Headers:

Content-Type: application/json
Body:

{
  "review": "This was an awesome spot!",
  "stars": 5,
}
Successful Response

Status Code: 201

Headers:

Content-Type: application/json
Body:

{
  "id": 1,
  "userId": 1,
  "spotId": 1,
  "review": "This was an awesome spot!",
  "stars": 5,
  "createdAt": "2021-11-19 20:39:36",
  "updatedAt": "2021-11-19 20:39:36"
}
Error Response: Body validation errors

Status Code: 400

Headers:

Content-Type: application/json
Body:

{
  "message": "Bad Request", // (or "Validation error" if generated by Sequelize),
  "errors": {
    "review": "Review text is required",
    "stars": "Stars must be an integer from 1 to 5",
  }
}
Error response: Couldn't find a Spot with the specified id

Status Code: 404

Headers:

Content-Type: application/json
Body:

{
  "message": "Spot couldn't be found"
}
Error response: Review from the current user already exists for the Spot

Status Code: 500

Headers:

Content-Type: application/json
Body:

{
  "message": "User already has a review for this spot"
}
