### ISSUE TITLE
Get all Reviews of the Current User

### ISSUE THREAD

**Issue by heather-yaple** [heather-yaple/auth-me-project#15]
Returns all the reviews written by the current user.

- [x]  An authenticated user is required for a successful response
- [x]  Successful response includes only reviews created by the current user
- [x]  Review data returned includes the id, userId, spotId, review, stars, createdAt, and updatedAt
- [x]  Review data returns associated data for User, including the id, firstName, and lastName
- [ ]  Review data returns associated data for Spot, including the id, ownerId, address, city, state, country, lat, lng, name, price, and previewImage
- [ ]  Review data returns associated data for ReviewImages, an array of image data including the id and url

**Comment by joe-corcoran** [comment]
Get all Reviews of the Current User
Returns all the reviews written by the current user.

Require Authentication: true

Request

Method: GET
Route path: /api/reviews/current
Body: none
Successful Response

Status Code: 200

Headers:

Content-Type: application/json
Body:

{
  "Reviews": [
    {
      "id": 1,
      "userId": 1,
      "spotId": 1,
      "review": "This was an awesome spot!",
      "stars": 5,
      "createdAt": "2021-11-19 20:39:36",
      "updatedAt": "2021-11-19 20:39:36" ,
      "User": {
        "id": 1,
        "firstName": "John",
        "lastName": "Smith"
      },
      "Spot": {
        "id": 1,
        "ownerId": 1,
        "address": "123 Disney Lane",
        "city": "San Francisco",
        "state": "California",
        "country": "United States of America",
        "lat": 37.7645358,
        "lng": -122.4730327,
        "name": "App Academy",
        "price": 123,
        "previewImage": "image url"
      },
      "ReviewImages": [
        {
          "id": 1,
          "url": "image url"
        }
      ]
    }
  ]
}

**Comment by heather-yaple** [comment]
Still need to include [ownerId, lat, lng, name, price, previewImage] for spot.

Still need to create information for Review Images [id, url]
