### ISSUE TITLE
Delete an Image for a Spot

### ISSUE THREAD

**Issue by heather-yaple** [heather-yaple/auth-me-project#24]
Delete an existing image for a Spot.

- [x]  An authenticated user is required for a successful response
- [x]  Only the owner of the spot is authorized to delete
- [x]  Image record is removed from the database after request
- [x]  Success response includes a message indicating a successful deletion
- [x]  Error response with status 404 is given when a spot image does not exist with the provided id

**Comment by joe-corcoran** [comment]
Delete a Spot Image
Delete an existing image for a Spot.

Require Authentication: true

Require proper authorization: Spot must belong to the current user

Request

Method: DELETE
Route path: /api/spot-images/:imageId
Body: none
Successful Response

Status Code: 200

Headers:

Content-Type: application/json
Body:

{
  "message": "Successfully deleted"
}
Error response: Couldn't find a Spot Image with the specified id

Status Code: 404

Headers:

Content-Type: application/json
Body:

{
  "message": "Spot Image couldn't be found"
}
