### ISSUE TITLE
Delete an Image for a Review

### ISSUE THREAD

**Issue by heather-yaple** [heather-yaple/auth-me-project#25]
Delete an existing image for a Review.

- [ ]  An authenticated user is required for a successful response
- [ ]  Only the owner of the review is authorized to delete
- [ ]  Image record is removed from the database after request
- [ ]  Success response includes a message indicating a successful deletion
- [ ]  Error response with status 404 is given when a review image does not exist with the provided id

**Comment by joe-corcoran** [comment]
Delete an existing image for a Review.

Require Authentication: true

Require proper authorization: Review must belong to the current user

Request

Method: DELETE
Route path: /api/review-images/:imageId
Body: none
Successful Response

Status Code: 200

Headers:

Content-Type: application/json
Body:

{
  "message": "Successfully deleted"
}
Error response: Couldn't find a Review Image with the specified id

Status Code: 404

Headers:

Content-Type: application/json
Body:

{
  "message": "Review Image couldn't be found"
}
