### ISSUE TITLE
Add an Image to a Spot based on the Spot's id

### ISSUE THREAD

**Issue by heather-yaple** [heather-yaple/auth-me-project#8]
Create and return a new image for a spot specified by id.

- [ ]  An authenticated user is required for a successful response
- [ ]  Only the owner of the spot is authorized to add an image
- [ ]  New image exists in the database after request
- [ ]  Image data returned includes the id, url, and preview
- [ ]  Error response with status 404 is given when a spot does not exist with the provided id

**Comment by joe-corcoran** [comment]
Add an Image to a Spot based on the Spot's id
Create and return a new image for a spot specified by id.

Require Authentication: true

Require proper authorization: Spot must belong to the current user

Request

Method: POST

Route path: /api/spots/:spotId/images

Headers:

Content-Type: application/json
Body:

{
  "url": "image url",
  "preview": true
}
Successful Response

Status Code: 201

Headers:

Content-Type: application/json
Body:

{
  "id": 1,
  "url": "image url",
  "preview": true
}
Error response: Couldn't find a Spot with the specified id

Status Code: 404

Headers:

Content-Type: application/json
Body:

{
  "message": "Spot couldn't be found"
}
