### ISSUE TITLE
Get all Spots owned by the Current User

### ISSUE THREAD

**Issue by heather-yaple** [heather-yaple/auth-me-project#9]
Returns all the spots owned (created) by the current user.

- [x]  An authenticated user is required for a successful response
- [x]  Successful response includes only spots created by the current user
- [x]  Spot data returned includes the id, ownerId, address, city, state, country, lat, lng, name, description, price, createdAt, updatedAt, previewImage, and avgRating

**Comment by joe-corcoran** [comment]
Get all Spots owned by the Current User
Returns all the spots owned (created) by the current user.

Require Authentication: true

Request

Method: GET
Route path: /api/spots/current
Body: none
Successful Response

Status Code: 200

Headers:

Content-Type: application/json
Body:

{
  "Spots": [
    {
      "id": 1,
      "ownerId": 1,
      "address": "123 Disney Lane",
      "city": "San Francisco",
      "state": "California",
      "country": "United States of America",
      "lat": 37.7645358,
      "lng": -122.4730327,
      "name": "App Academy",
      "description": "Place where web developers are created",
      "price": 123,
      "createdAt": "2021-11-19 20:39:36",
      "updatedAt": "2021-11-19 20:39:36",
      "avgRating": 4.5,
      "previewImage": "image url"
    }
  ]
}
